[package]
name = "example"
version = "0.1.0"
authors = ["Thomas Herzog <thomas.herzog@simedis.com>"]

[dependencies]
nitrogen = { path = "../nitrogen", features = ["winit"] }
winit = "0.17.2"
image = "0.20.0"
log = "0.4.5"
env_logger = "0.5.13"