[package]
name = "nitrogen-examples-common"
version = "0.1.0"
publish = false
authors = ["Thomas Herzog <thomas.herzog@simedis.com>"]
edition = "2018"

[dependencies]
nitrogen = { path = "../../nitrogen" }
winit = "0.17.0"