[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Thomas Herzog <thomas.herzog@simedis.com>"]



[features]
default = ["winit_support"]
winit_support = ["gfx-backend-vulkan/winit", "winit"]
x11 = []



[dependencies]
ash = "0.24.4"
slab = "0.4.1"
failure = "0.1.2"
failure_derive = "0.1.2"
shaderc = "0.3.11"

winit = { version = "0.17.2", optional = true }

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "bdabfc00f4e259e8650a78451c8d7b7782d18ed4"
default-features = false

[dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
rev = "bdabfc00f4e259e8650a78451c8d7b7782d18ed4"
default-features = false

[dependencies.gfx-memory]
# git = "https://github.com/gfx-rs/gfx-memory"
path = "../../../staging/gfx-memory"

