[package]
name = "nitrogen"
version = "0.1.0"
authors = ["Thomas Herzog <thomas.herzog@simedis.com>"]



[features]
default = ["winit_support"]
winit_support = ["gfx-backend-vulkan/winit", "winit"]
x11 = []



[dependencies]
ash = "0.24.4"
slab = "0.4.1"
failure = "0.1.2"
failure_derive = "0.1.2"
shaderc = "0.3.11"
bitflags = "1.0.4"
smallvec = "0.6.5"
winit = { version = "0.17.2", optional = true }

[dependencies.gfx-hal]
git = "https://github.com/gfx-rs/gfx"
rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7"
default-features = false

[dependencies.gfx-backend-vulkan]
git = "https://github.com/gfx-rs/gfx"
rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7"
default-features = false

[dependencies.gfx-memory]
# git = "https://github.com/gfx-rs/gfx-memory"
path = "../../../staging/gfx-memory"

