[package]
name = "nitrogen-ffi"
version = "0.1.0"
authors = ["Thomas Herzog <thomas.herzog@simedis.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
nitrogen = { path = "../nitrogen" }

[build-dependencies]
cbindgen = "0.6.3"
